export component HelpInfo {
    out property <string> content:
"1. When you run the app, the system current adapters are loaded to the list in `Adapters`, or you can click `Refresh` to reload.\n" +
"2. Choose one of the adapters to see details.\n" +
"3. Select one in step 2, then click `Load selected`. The adapter info is loaded to the left area.\n" +
"4. Do some change in the left area, click `Apply` or `Save` when you finished, or `Load selected` to discard the changes.\n" +
"     1) The app support multiple ip when `dpch on` is unchecked. Each line represent one address. Please fill the `ip` and `netmask` list with same count, while each ip must match a netmask.\n" +
"     2) `gateway` and `dns list` also support multiple address.\n" +
"\n" +
"If you saved some items in step 4, then you can choose and select them, like step 2 & 3.";
}
