import {ScrollView, LineEdit , Button, CheckBox, HorizontalBox, VerticalBox, Switch, TextEdit} from "std-widgets.slint";

export struct IpV4 {
    ip : string,
}

export struct NetAddress {
    ip : IpV4,
    netmask : IpV4,
}

export struct NetInterfaceItem {
    index : int,
    guid : string,
    name : string,
    is_up : bool,
    address : [NetAddress],
    gateway : [IpV4],
    dns : [IpV4],
    dhcp_server : IpV4,
}

export global InterfaceItemCheck {
    callback check-ip(IpV4) -> bool;
    callback check-address(NetAddress) -> bool;
}

export global NetItemUtils {
    callback get-ip-list([NetAddress]) -> string;
    callback get-netmask-list([NetAddress]) -> string;
    callback get-gateway-list([IpV4]) -> string;
    callback get-dns-list([IpV4]) -> string;
}

component IpItem {
    in-out property <string> name : "IP";
    in-out property <IpV4> ip : {ip:""};
    in-out property <bool> read-only;
    in-out property <length> font-size;
    in-out property <bool> valid;
    in-out property <length> name-width;

    property <bool> state-sign : true;
    property <float> warning-state: 0;

    callback check-ip(IpV4) -> bool;
    check-ip(t) => {
        root.ip = t;
        root.valid = !InterfaceItemCheck.check-ip(root.ip);

        if (!root.valid) {
            if (root.state-sign) {
                root.warning-state = 0;
            } else {
                root.warning-state = 1;
            }
            root.state-sign = !root.state-sign;
        }

        root.valid
    }
    
    animate warning-state {
        duration: 3s;
    }

    // VerticalLayout {
        // HorizontalLayout { 
        //     Button { text: "valid";  clicked => { root.valid = !root.valid; }}
        //     Button { text: "change"; clicked => {
        //         if (root.state-sign) {
        //             root.warning-state = 0;
        //             root.state-sign = false;
        //         } else {
        //             root.warning-state = 1;
        //             root.state-sign = true;
        //         }
        //     }}

        //     if root.valid : Text { text: "valid: true , state \{Math.round(root.warning-state *100)/100}";}
        //     if !root.valid : Text { text: "valid: false , state \{Math.round(root.warning-state *100)/100}";}
        // }
        HorizontalBox { 
            // padding-left: 8px;
            // padding-right: 8px;

            alignment: stretch;
            Text { text: root.name ; vertical-alignment: center; width: root.name-width; font-size: root.font-size;}
            Rectangle {
                // horizontal-stretch: 1;
                le := LineEdit { 
                    text: root.ip.ip; 
                    x : 0;
                    width: 100%;
                    font-size: root.font-size;
                    read-only: root.read-only;
                    accepted(t) => { 
                        check-ip({ip: t});
                    }
                }

                warning-format-text := Text { text: "format error!"; color: #CC5555AB; x : le.width - self.width - 10px; }
                states [
                    normal when root.valid || (root.warning-state == 0 && root.state-sign ) || (root.warning-state== 1 && !root.state-sign): {
                        warning-format-text.color : #CC555500;
                    }
                    warning when !root.valid && ((root.warning-state!= 0 && root.warning-state < 0.6 && root.state-sign)
                        || (root.warning-state!= 1 && root.warning-state > 0.4 && !root.state-sign)) : {
                        warning-format-text.color : #CC5555AB;

                        out {
                            animate warning-format-text.color { duration: 1.5s;}
                        }
                    }
                    left when !root.valid && ((root.warning-state >= 0.6 && root.state-sign) || (root.warning-state<=0.4 && !root.state-sign)) : {
                        warning-format-text.color : #CC555500;
                    }
                ]

            }
        }
    // }
}

export component InterfaceUiItem inherits Rectangle{
    in-out property <NetInterfaceItem> value;
    in property <bool> read-only;
    in-out property <bool> collapsed : false;

    property <length> name-width : 48px;

    states [
        show-all when !collapsed: {
            content.visible : true;
            mini-name.visible : false;
        }
        show-name when collapsed: {
            content.visible : false;
            mini-name.visible : true;
        }
    ]
    
    Rectangle {
        border-color: gray;
        border-width: 2px;
        border-radius: 5px;
    }

    VerticalLayout {
        padding: 8px;

        ScrollView {
            mini-name := HorizontalBox {
                Text { text: "name"; width: root.name-width; vertical-alignment: center;}
                LineEdit { text: value.name; read-only: root.read-only; accepted => { root.collapsed = false;}}
            }
            content := VerticalBox {

                HorizontalBox {
                    Text { text: "index"; width: root.name-width; vertical-alignment: center;}
                    LineEdit { text: value.index; read-only: root.read-only;}
                }

                HorizontalBox {
                    Text { text: "guid"; width: root.name-width; vertical-alignment: center;}
                    LineEdit { text: value.guid; read-only: root.read-only;}
                }

                HorizontalBox {
                    Text { text: "name"; width: root.name-width; vertical-alignment: center;}
                    LineEdit { text: value.name; read-only: root.read-only; accepted => { root.collapsed = true; }}
                }

                Rectangle {
                    HorizontalBox {
                        // Text { text: "state"; width: root.name-width; vertical-alignment: center;}
                        Switch { text: "is up"; checked: value.is-up; }
                        Switch { text: "dhcp on"; checked: value.dhcp-server.ip != ""; }
                    }
                    if read-only : TouchArea{}
                }

                Rectangle {
                    // Rectangle {
                        border-color: gray;
                        border-width: 2px;
                        border-radius: 5px;
                    // }
                    VerticalBox {
                        // spacing: 10px;
                        // padding: 6px;
                        Text { text: "address list";}
                        for item in  root.value.address: HorizontalBox {
                            IpItem {name: "ip"; ip: item.ip;}
                            IpItem {name: "netmask"; ip: item.netmask;}
                        }
                    }

                }

                Rectangle {
                    // Rectangle {
                        border-color: gray;
                        border-width: 2px;
                        border-radius: 5px;
                    // }
                    VerticalBox {
                        // padding: 6px;
                        // spacing: 10px;
                        Text { text: "gateway list";}
                        for item in  root.value.gateway: HorizontalBox {
                            IpItem {name: "ip"; ip: item;}
                        }
                    }
                }

                Rectangle {
                    // Rectangle {
                        border-color: gray;
                        border-width: 2px;
                        border-radius: 5px;
                    // }
                    VerticalBox {
                        // spacing: 10px;
                        // padding: 6px;
                        Text { text: "dns list";}
                        for item in  root.value.dns: HorizontalBox {
                            IpItem {name: "ip"; ip: item;}
                        }
                    }
                }

                Rectangle {}
            }
        }
    }
}

export component InterfaceEdit inherits Rectangle{
    in-out property <NetInterfaceItem> value;
    in-out property <bool> dhcp-on;

    property <length> name-width : 48px;

    public function select-item(item : NetInterfaceItem) 
    {
        value = item;

        te-ip.text = NetItemUtils.get-ip-list(item.address);
        te-netmask.text = NetItemUtils.get-netmask-list(item.address);
        te-gateway.text = NetItemUtils.get-gateway-list(item.gateway);
        te-dns.text = NetItemUtils.get-dns-list(item.dns);
        root.dhcp-on = item.dhcp-server.ip != "";
    }

    Rectangle {
        border-color: gray;
        border-width: 2px;
        border-radius: 5px;
    }

    VerticalLayout {
        padding: 8px;

        ScrollView {
            VerticalBox {

                HorizontalBox {
                    Text { text: "index"; width: root.name-width; vertical-alignment: center;}
                    LineEdit { text: value.index; read-only: true; }
                }

                HorizontalBox {
                    Text { text: "guid"; width: root.name-width; vertical-alignment: center;}
                    LineEdit { text: value.guid;  read-only: true;}
                }

                HorizontalBox {
                    Text { text: "name"; width: root.name-width; vertical-alignment: center;}
                    LineEdit { text: value.name;  read-only: true;}
                }

                Rectangle {
                    HorizontalBox {
                        sw-dhcp := Switch { text: "dhcp on"; checked: root.dhcp-on;}
                    }
                }

                states [
                    show-dhcp when sw-dhcp.checked : {
                        ui-address.visible : true;
                        ui-gateway.visible : true;
                        ui-dns.visible : true;
                        ui-space.visible : false;
                    }
                    show-static when !sw-dhcp.checked : {
                        ui-address.visible : false;
                        ui-gateway.visible : false;
                        ui-dns.visible : false;
                        ui-space.visible : true;
                    }
                ]
                ui-address:= Rectangle {
                    border-color: gray;
                    border-width: 2px;
                    border-radius: 5px;

                    VerticalBox {
                        Text { text: "address list";}
                        HorizontalBox {
                            min-height: 64px;
                            Text {text: "ip";}
                            te-ip := TextEdit {}
                            Text {text: "netmask";}
                            te-netmask := TextEdit {}
                        }
                    }

                }

                ui-gateway := Rectangle {
                    // Rectangle {
                        border-color: gray;
                        border-width: 2px;
                        border-radius: 5px;
                    // }
                    VerticalBox {
                        Text { text: "gateway list";}
                        te-gateway := TextEdit {}
                    }
                }

                ui-dns := Rectangle {
                    // Rectangle {
                        border-color: gray;
                        border-width: 2px;
                        border-radius: 5px;
                    // }
                    VerticalBox {
                        Text { text: "dns list";}
                        te-dns := TextEdit {}
                    }
                }

                ui-space := Rectangle{ }
            }
        }
    }
}