import { LineEdit , Button, CheckBox, VerticalBox, HorizontalBox, ListView, StandardListView, GridBox} from "std-widgets.slint";
import { IpV4, NetAddress, NetInterfaceItem, InterfaceUiItem, InterfaceItemCheck, InterfaceEdit, NetItemUtils } from "interface-item.slint";
import { PopMessageBox } from "pop-message.slint";
import { HelpInfo } from "help-info.slint";
export { InterfaceItemCheck, NetItemUtils }

export global NetInterfaceStatus {
    in-out property <[NetInterfaceItem]> interface-infos; 
    in-out property <[StandardListViewItem]> interface-names;
    in-out property <int> selected-index;
    in-out property <[NetInterfaceItem]> saved-settings; 
    in-out property <[StandardListViewItem]> saved-names;
}

export component Main inherits Window {
    preferred-width: 1280px;
    preferred-height: 720px;

    in-out property <bool> select-system-adapter : false;
    out property <string> selected_guid;

    public function select-system(index:int) {
        listview-system.set-current-item(index);
    }

    public function show-message-box(title:string, text:string) {
        message-box.title = title;
        message-box.text = text;
        message-box.visible = true;
        message-box.focus();

        message-box.content-width = 300px;
        message-box.content-height = 160px;
    }


    callback set-static(string, NetInterfaceItem);
    callback set-dynamic(string);
    callback refresh-adapters();
    callback load-selected(NetInterfaceItem);
    callback remove-selected(int);
    callback apply-config(NetInterfaceItem, bool, [string]);
    callback save-config(NetInterfaceItem, bool, [string]);

    title: "Config Ip Tool";

    message-box := PopMessageBox{ }

    HorizontalBox {
        Rectangle {
            border-width: 1px;
            border-color: #666;
            border-radius: 8px;
            width: parent.width * 0.4;

            VerticalBox {
                HorizontalLayout {
                    Text {text: "Edit interface"; max-height: 20px; vertical-alignment: center;}
                    Rectangle { horizontal-stretch: 2;}
                    Button {text: "Help"; clicked => {
                        show-message-box("Help", help-info.content);
                        message-box.content-width = 840px;
                        message-box.content-height = 360px;
                    }}
                    help-info := HelpInfo{ width: 0; height: 0;}
                }
                HorizontalBox {
                    Button {text: "Apply"; clicked => {
                        apply-config(curr.value, curr.dhcp-on, curr.get-items());
                    }}
                    Button {text: "Save"; clicked => {
                        save-config(curr.value, curr.dhcp-on, curr.get-items());
                    }}
                    Button {text: "Load selected"; clicked => {
                        curr.select-item(show-setting.value);
                    }}
                }

                curr := InterfaceEdit { }
            }
        }

        Rectangle {
            border-width: 1px;
            border-color: #666;
            border-radius: 8px;

            GridBox {
                Row {
                    Text {text: "Adapters"; max-height: 20px; vertical-alignment: center;}
                    Button {text: "Refresh"; clicked => { root.refresh-adapters(); }}
                }
                Row {
                    listview-system := StandardListView { 
                        colspan: 2;
                        model: NetInterfaceStatus.interface-names;
                        current-item-changed(index) => {
                            if (index>=0 && index < NetInterfaceStatus.interface-infos.length) {
                                show-setting.value = NetInterfaceStatus.interface-infos[index];
                                root.select-system-adapter = true;
                                root.selected-guid = show-setting.value.guid;
                                le-selected-item.text = "Adapter : " + show-setting.value.name;
                            }
                        }
                    }
                }
                Row {
                    Rectangle {
                        colspan: 2;
                        height: 3px;
                        background: @linear-gradient(90deg, #e99 0%, #9e9 50%, #99e 100%);
                    }
                }
                Row {
                    Text {text: "Saved settings"; max-height: 20px; vertical-alignment: center;}
                    Button {text: "Remove"; clicked => {
                        if (listview-saved.current-item >= 0) {
                            root.remove-selected(listview-saved.current-item);
                        }
                    }}
                }
                Row {
                    listview-saved := StandardListView { 
                        colspan: 2;
                        model: NetInterfaceStatus.saved-names;
                        current-item-changed(index) => {
                            if (index>=0 && index < NetInterfaceStatus.saved-settings.length) {
                                show-setting.value = NetInterfaceStatus.saved-settings[index];
                                root.select-system-adapter = false;
                                root.selected-guid = show-setting.value.guid;
                                le-selected-item.text = "Saved : " + show-setting.value.name;
                            }
                        }
                    }
                }

            }
            
        }

        Rectangle {
            border-width: 1px;
            border-color: #666;
            border-radius: 8px;
            width: parent.width * 0.4;

            VerticalBox {
                HorizontalBox {
                    Text {text: "Selected Item"; vertical-alignment: center;}
                    le-selected-item := LineEdit { read-only: true; }
                }

                show-setting := InterfaceUiItem { 
                    read-only: true;
                }
            }

        }
    }

    
}
