import {Button, VerticalBox} from "std-widgets.slint";

export component PopMessageBox inherits Rectangle{
    background: #20202080;
    // visible: false;

    in property <string> title : "title";
    in property <string> text : "text";
    in property <color> style-border-color : #333;

    z: 1;

    // mask the whole window, to disable interacting
    TouchArea { z: 2;}
    Rectangle {
        width: 300px;
        height: 160px;
        x: (root.width - self.width) / 2 ;
        y: (root.height - self.height) / 2 ;
        z: 3;

        border-color: root.style-border-color;
        border-width: 1px;
        border-radius: 12px;
        background: #ddd;

        VerticalBox {
            x: 8px;
            width: parent.width - self.x * 2;
            y: 6px;
            height: parent.height - self.y * 2;
            z: 4;
            Text { text: root.title; }
            Rectangle { width: parent.width * 0.4; height: 1px; background: root.style-border-color; }
            Text { vertical-stretch: 1; text: root.text; }
            Rectangle { Button { 
                text: "Ok";
                x: (parent.width - self.width)/2 ;
                width: 120px;
                clicked => { root.visible = false; }
            }}
        }
    }
}