import {Button, VerticalBox} from "std-widgets.slint";

export component PopMessageBox inherits Rectangle{
    forward-focus: btn-ok;
    background: #20202080;
    visible: false;

    in property <length> content-width: 300px;
    in property <length> content-height: 160px;

    in property <string> title : "title";
    in property <string> text : "text";
    in property <color> style-border-color : #333;

    // mask the whole window, to disable interacting
    TouchArea { 
    }
    Rectangle {
        width: content-width;
        height: content-height;
        x: (root.width - self.width) / 2 ;
        y: (root.height - self.height) / 2 ;

        border-color: root.style-border-color;
        border-width: 1px;
        border-radius: 12px;
        background: #ddd;

        VerticalBox {
            x: 8px;
            width: parent.width - self.x * 2;
            y: 6px;
            height: parent.height - self.y * 2;
            Text { text: root.title; font-size: 20px;}
            Rectangle { width: parent.width * 0.4; height: 1px; background: root.style-border-color; }
            Text { 
                vertical-stretch: 1;
                text: root.text;
                wrap: TextWrap.word-wrap;
                font-size: 16px;
            }
            Rectangle { 
                btn-ok := Button { 
                    text: "Ok";
                    x: (parent.width - self.width)/2 ;
                    width: 120px;
                    clicked => { root.visible = false; }
                }
            }
        }
    }
}